### ISSUE TITLE
Remove warning for names ending with a non-alphanumeric char?

### ISSUE THREAD

**Issue by mathiasbynens** [sindresorhus/validate-element-name#9]
@domenic pointed out that maybe we should rethink this restriction. Why is it still there? We already warn for things like `.` or non-ASCII symbols anywhere in the name, which takes care of most/all confusion-inducing custom element names I can think of right now.

```js
	if (/[^a-z0-9]$/i.test(name)) {
		return 'Custom element names should not end with a non-alpha character.';
	}
```

I think this was [originally](https://github.com/mathiasbynens/mothereff.in/issues/29) added to warn on things like `foo-`. Maybe we should loosen up this rule and warn on a `-` suffix instead?

**Comment by sindresorhus** [comment]
It was added here https://github.com/sindresorhus/validate-element-name/commit/9ccb4807883bb6765fe4c84013a0984e20663174 in response to https://github.com/mathiasbynens/mothereff.in/issues/29#issuecomment-40196030. I'd say we revert to the old check for trailing hyphen. ?

**Comment by mathiasbynens** [comment]
SGTM 👍
